<?php
/**
 * AlbumsCriteria allows custom querying for the Albums object.  Here you may
 * add properties that will translate into SQL.  Included are the basic fields that can 
 * be used as a typical "query by example" however you may add properties that do not
 * directly relate to fields or use other types of logic.
 *
 * This file is automatically generated by ClassBuilder.
 *
 * @package    Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
 
require_once("verysimple/Phreeze/Criteria.php");
	
class AlbumsCriteria extends Criteria
{
	/**
	 * Phreeze parses all of the properties in the Criteria class and knows how to process
	 * any that end in the following _Equals, _IsLike, _BeginsWith, _EndsWith, _GreaterThan, LessThan.
	 * If you wish to add any criteria parameters beyond these, you must override OnPrepare
	 */
	public $Id_Equals;
	public $Id_IsLike;
	public $Id_BeginsWith;
	public $Id_EndWith;
	public $Id_GreaterThan;
	public $Id_LessThan;
	public $BandName_Equals;
	public $BandName_IsLike;
	public $BandName_BeginsWith;
	public $BandName_EndWith;
	public $BandName_GreaterThan;
	public $BandName_LessThan;
	public $AlbumName_Equals;
	public $AlbumName_IsLike;
	public $AlbumName_BeginsWith;
	public $AlbumName_EndWith;
	public $AlbumName_GreaterThan;
	public $AlbumName_LessThan;
	public $ReleaseDate_Equals;
	public $ReleaseDate_IsLike;
	public $ReleaseDate_BeginsWith;
	public $ReleaseDate_EndWith;
	public $ReleaseDate_GreaterThan;
	public $ReleaseDate_LessThan;
	public $CoverArt_Equals;
	public $CoverArt_IsLike;
	public $CoverArt_BeginsWith;
	public $CoverArt_EndWith;
	public $CoverArt_GreaterThan;
	public $CoverArt_LessThan;
	public $Credits_Equals;
	public $Credits_IsLike;
	public $Credits_BeginsWith;
	public $Credits_EndWith;
	public $Credits_GreaterThan;
	public $Credits_LessThan;

	/**
	 * For custom query logic, you may override OnProcess and set the $this->_where to whatever
	 * sql code is necessary.  If you choose to manually set _where then Phreeze will not touch
	 * your where clause at all and so any of the standard property names will be ignored
	 */
	/*
	function OnPrepare()
	{
		if ($this->MyCustomField == "special value")
		{
			// _where must begin with "where"
			$this->_where = "where db_field ....";
		}
	}
	*/
}

?>