<?php
/**
 * AlbumsMap is a static class with functions used to get FieldMap and KeyMap information that
 * is used by Phreeze to map the AlbumsDAO to the albums datastore.
 *
 * This file is automatically generated by ClassBuilder.
 *
 * This file should generally not be edited by hand except in special circumstances.
 * You can override the default fetching strategies for KeyMaps in _config.php.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package    Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
 
require_once("verysimple/Phreeze/IDaoMap.php");

	
class AlbumsMap implements IDaoMap
{
	/**
	 * Returns a singleton array of FieldMaps for the Albums object
	 *
	 * @access static
	 * @return array of FieldMaps
	 */
	public static function GetFieldMaps()
	{
		static $fm = null;
		if ($fm == null)
		{
			$fm = Array();
			$fm["Id"] = new FieldMap("Id","albums","a_id",true,FM_TYPE_INT,11,null,true);
			$fm["BandName"] = new FieldMap("BandName","albums","a_band_name",false,FM_TYPE_VARCHAR,100,null,false);
			$fm["AlbumName"] = new FieldMap("AlbumName","albums","a_album_name",false,FM_TYPE_TEXT,null,null,false);
			$fm["ReleaseDate"] = new FieldMap("ReleaseDate","albums","a_release_date",false,FM_TYPE_TEXT,null,null,false);
			$fm["CoverArt"] = new FieldMap("CoverArt","albums","a_cover_art",false,FM_TYPE_TEXT,null,null,false);
			$fm["Credits"] = new FieldMap("Credits","albums","a_credits",false,FM_TYPE_TEXT,null,null,false);
		}
		return $fm;
	}
	
	/**
	 * Returns a singleton array of KeyMaps for the Albums object
	 *
	 * @access static
	 * @return array of KeyMaps
	 */
	public static function GetKeyMaps()
	{
		static $km = null;
		if ($km == null)
		{
			$km = Array();
			$km["fa_album_id"] = new KeyMap("fa_album_id", "Id", "FanArt", "AlbumId", KM_TYPE_ONETOMANY, KM_LOAD_LAZY);  // use KM_LOAD_EAGER with caution here (one-to-one relationships only)
			$km["p_album_id"] = new KeyMap("p_album_id", "Id", "Press", "AlbumId", KM_TYPE_ONETOMANY, KM_LOAD_LAZY);  // use KM_LOAD_EAGER with caution here (one-to-one relationships only)
			$km["s_album_id"] = new KeyMap("s_album_id", "Id", "Songs", "AlbumId", KM_TYPE_ONETOMANY, KM_LOAD_LAZY);  // use KM_LOAD_EAGER with caution here (one-to-one relationships only)
		}
		return $km;
	}
	
}

?>