<?php
/**
 * EmailListMap is a static class with functions used to get FieldMap and KeyMap information that
 * is used by Phreeze to map the EmailListDAO to the email_list datastore.
 *
 * This file is automatically generated by ClassBuilder.
 *
 * This file should generally not be edited by hand except in special circumstances.
 * You can override the default fetching strategies for KeyMaps in _config.php.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package    Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
 
require_once("verysimple/Phreeze/IDaoMap.php");

	
class EmailListMap implements IDaoMap
{
	/**
	 * Returns a singleton array of FieldMaps for the EmailList object
	 *
	 * @access static
	 * @return array of FieldMaps
	 */
	public static function GetFieldMaps()
	{
		static $fm = null;
		if ($fm == null)
		{
			$fm = Array();
			$fm["Id"] = new FieldMap("Id","email_list","el_id",true,FM_TYPE_INT,11,null,true);
			$fm["Address"] = new FieldMap("Address","email_list","el_address",false,FM_TYPE_VARCHAR,100,null,false);
		}
		return $fm;
	}
	
	/**
	 * Returns a singleton array of KeyMaps for the EmailList object
	 *
	 * @access static
	 * @return array of KeyMaps
	 */
	public static function GetKeyMaps()
	{
		static $km = null;
		if ($km == null)
		{
			$km = Array();
		}
		return $km;
	}
	
}

?>