<?php
/**
 * FanArtMap is a static class with functions used to get FieldMap and KeyMap information that
 * is used by Phreeze to map the FanArtDAO to the fan_art datastore.
 *
 * This file is automatically generated by ClassBuilder.
 *
 * This file should generally not be edited by hand except in special circumstances.
 * You can override the default fetching strategies for KeyMaps in _config.php.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package    Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
 
require_once("verysimple/Phreeze/IDaoMap.php");

	
class FanArtMap implements IDaoMap
{
	/**
	 * Returns a singleton array of FieldMaps for the FanArt object
	 *
	 * @access static
	 * @return array of FieldMaps
	 */
	public static function GetFieldMaps()
	{
		static $fm = null;
		if ($fm == null)
		{
			$fm = Array();
			$fm["Id"] = new FieldMap("Id","fan_art","fa_id",true,FM_TYPE_INT,11,null,false);
			$fm["Image"] = new FieldMap("Image","fan_art","fa_image",false,FM_TYPE_TINYTEXT,null,null,false);
			$fm["Submitter"] = new FieldMap("Submitter","fan_art","fa_submitter",false,FM_TYPE_VARCHAR,100,null,false);
			$fm["AlbumId"] = new FieldMap("AlbumId","fan_art","fa_album_id",false,FM_TYPE_INT,11,null,false);
		}
		return $fm;
	}
	
	/**
	 * Returns a singleton array of KeyMaps for the FanArt object
	 *
	 * @access static
	 * @return array of KeyMaps
	 */
	public static function GetKeyMaps()
	{
		static $km = null;
		if ($km == null)
		{
			$km = Array();
			$km["fa_album_id"] = new KeyMap("fa_album_id", "AlbumId", "Albums", "Id", KM_TYPE_MANYTOONE, KM_LOAD_LAZY); // you change to KM_LOAD_EAGER here or (preferrably) make the change in _config.php
		}
		return $km;
	}
	
}

?>