<?php
/**
 * VideosMap is a static class with functions used to get FieldMap and KeyMap information that
 * is used by Phreeze to map the VideosDAO to the videos datastore.
 *
 * This file is automatically generated by ClassBuilder.
 *
 * This file should generally not be edited by hand except in special circumstances.
 * You can override the default fetching strategies for KeyMaps in _config.php.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package    Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
 
require_once("verysimple/Phreeze/IDaoMap.php");

	
class VideosMap implements IDaoMap
{
	/**
	 * Returns a singleton array of FieldMaps for the Videos object
	 *
	 * @access static
	 * @return array of FieldMaps
	 */
	public static function GetFieldMaps()
	{
		static $fm = null;
		if ($fm == null)
		{
			$fm = Array();
			$fm["Id"] = new FieldMap("Id","videos","v_id",true,FM_TYPE_INT,11,null,false);
			$fm["Name"] = new FieldMap("Name","videos","v_name",false,FM_TYPE_VARCHAR,100,null,false);
			$fm["SongId"] = new FieldMap("SongId","videos","v_song_id",false,FM_TYPE_INT,11,null,false);
		}
		return $fm;
	}
	
	/**
	 * Returns a singleton array of KeyMaps for the Videos object
	 *
	 * @access static
	 * @return array of KeyMaps
	 */
	public static function GetKeyMaps()
	{
		static $km = null;
		if ($km == null)
		{
			$km = Array();
			$km["v_song_id"] = new KeyMap("v_song_id", "SongId", "Songs", "Id", KM_TYPE_MANYTOONE, KM_LOAD_LAZY); // you change to KM_LOAD_EAGER here or (preferrably) make the change in _config.php
		}
		return $km;
	}
	
}

?>