<?php
/**
 * EmailListController is the controller class for the EmailList object
 *
 * @author Generated by ClassBuilder
 * @version 1.0
 */
 
require_once("verysimple/Phreeze/Controller.php");
require_once("Model/EmailList.php");

class EmailListController extends Controller
{

	protected function Init()
	{
		$this->ModelName = "EmailList";
	}
	
	// base functions suggested to override
	// function ListAll() {}

	function ListPage()
	{
		// these parameters are supplied by extjs grid pagingtoolbar
		$s = Request::Get('start',0);  // start (zero based)
		$ps = Request::Get('limit',20); // page size
		$sc = Request::Get('sort'); // name of column for sorting
		$sd = Request::Get('dir','ASC'); // sort direction
		$cp = $s/$ps + 1; // current page
		
		require_once("Model/DAO/EmailListCriteria.php");
		$criteria = new EmailListCriteria();
		
		// if a sort was specified, add it to the criteria
		if ($sc)
		{
			$criteria->SetOrder($sc, ($sd == "ASC") );
		}
		
		$datapage = $this->Phreezer->Query("EmailList",$criteria)->GetDataPage($cp,$ps);
		
		$this->RenderXML($datapage);
	}
	
	function Display()
	{
		$this->_AssignModel(Request::Get("Id"));
		$this->Render("EmailListDisplay");
	}

	function Edit()
	{
		$this->_AssignModel(Request::Get("Id"));
		$this->Render("EmailListEdit");
	}
	
	function Create()
	{
		$this->_AssignModel();
		$this->Render("EmailListEdit");
	}
	
	function Save()
	{
		$pk = Request::Get("Id");
		
		$emaillist = $this->LoadFromForm($pk);
		
		if (!$emaillist->Validate())
		{
			$this->Assign("emaillist", $emaillist);
			$this->_AssignChildren($emaillist);
			$this->Assign("warning",implode("<br />",$emaillist->GetValidationErrors()));
			$this->Render("EmailListEdit");
		}
		else
		{
			try
			{
				$emaillist->Save();
				$this->Redirect("EmailList.ListAll","EmailList was saved");
			}
			catch(Exception $ex)
			{
				$this->Assign("emaillist", $emaillist);
				$this->_AssignChildren($emaillist);
				$this->Assign("warning",$ex->getMessage());
				$this->Render("EmailListEdit");
			}

		}
	}

	function Delete()
	{
		$pk = Request::Get("Id");
		$emaillist = $this->Phreezer->Get("EmailList",$pk);
		$emaillist->Delete();
		$this->Redirect("EmailList.ListAll","EmailList was deleted");
	}

	private function _AssignModel($pk = null, $assign_children = true)
	{
		$emaillist = $pk ? $this->Phreezer->Get("EmailList",$pk) : New EmailList($this->Phreezer);
		$this->Assign("emaillist", $emaillist);

		if ($assign_children)
		{
			$this->_AssignChildren($emaillist);
		}
	}

	
	protected function LoadFromForm($pk = null)
	{
		$emaillist = $pk ? $this->Phreezer->Get("EmailList",$pk) : New EmailList($this->Phreezer);
		// $emaillist->Id = Request::Get("Id"); // this is an auto-increment
		$emaillist->Address = Request::Get("Address");
		
		return $emaillist;
	}
	
	private function _AssignChildren($emaillist)
	{
	}
}

?>