<?php
/**
 * FanArtController is the controller class for the FanArt object
 *
 * @author Generated by ClassBuilder
 * @version 1.0
 */
 
require_once("verysimple/Phreeze/Controller.php");
require_once("Model/FanArt.php");

class FanArtController extends Controller
{

	protected function Init()
	{
		$this->ModelName = "FanArt";
	}
	
	// base functions suggested to override
	// function ListAll() {}

	function ListPage()
	{
		// these parameters are supplied by extjs grid pagingtoolbar
		$s = Request::Get('start',0);  // start (zero based)
		$ps = Request::Get('limit',20); // page size
		$sc = Request::Get('sort'); // name of column for sorting
		$sd = Request::Get('dir','ASC'); // sort direction
		$cp = $s/$ps + 1; // current page
		
		require_once("Model/DAO/FanArtCriteria.php");
		$criteria = new FanArtCriteria();
		
		// if a sort was specified, add it to the criteria
		if ($sc)
		{
			$criteria->SetOrder($sc, ($sd == "ASC") );
		}
		
		$datapage = $this->Phreezer->Query("FanArt",$criteria)->GetDataPage($cp,$ps);
		
		$this->RenderXML($datapage);
	}
	
	function Display()
	{
		$this->_AssignModel(Request::Get("Id"));
		$this->Render("FanArtDisplay");
	}

	function Edit()
	{
		$this->_AssignModel(Request::Get("Id"));
		$this->Render("FanArtEdit");
	}
	
	function Create()
	{
		$this->_AssignModel();
		$this->Render("FanArtEdit");
	}
	
	function Save()
	{
		$pk = Request::Get("Id");
		
		$fanart = $this->LoadFromForm($pk);
		
		if (!$fanart->Validate())
		{
			$this->Assign("fanart", $fanart);
			$this->_AssignChildren($fanart);
			$this->Assign("warning",implode("<br />",$fanart->GetValidationErrors()));
			$this->Render("FanArtEdit");
		}
		else
		{
			try
			{
				// this table does not have an auto-insert, so we have to specify an insert
				$force_insert = Request::Get("force_insert");
				$fanart->Save($force_insert);
				$this->Redirect("FanArt.ListAll","FanArt was saved");
			}
			catch(Exception $ex)
			{
				$this->Assign("fanart", $fanart);
				$this->_AssignChildren($fanart);
				$this->Assign("warning",$ex->getMessage());
				$this->Render("FanArtEdit");
			}

		}
	}

	function Delete()
	{
		$pk = Request::Get("Id");
		$fanart = $this->Phreezer->Get("FanArt",$pk);
		$fanart->Delete();
		$this->Redirect("FanArt.ListAll","FanArt was deleted");
	}

	private function _AssignModel($pk = null, $assign_children = true)
	{
		$fanart = $pk ? $this->Phreezer->Get("FanArt",$pk) : New FanArt($this->Phreezer);
		$this->Assign("fanart", $fanart);

		if ($assign_children)
		{
			$this->_AssignChildren($fanart);
		}
	}

	
	protected function LoadFromForm($pk = null)
	{
		// the primary key of this table is not an auto-insert
		$fanart = New FanArt($this->Phreezer);
		$fanart->Id = Request::Get("Id");
		$fanart->Image = Request::Get("Image");
		$fanart->Submitter = Request::Get("Submitter");
		$fanart->AlbumId = Request::Get("AlbumId");
		
		return $fanart;
	}
	
	private function _AssignChildren($fanart)
	{
		// get possible values for AlbumId and assign as a value pair for html_options
		$album_ids = array();
		$collection = $this->Phreezer->Query("Albums");
		while ($album_id = $collection->Next())
		{
			$album_ids[$album_id->Id] = $album_id->BandName; // TODO: verify this is the right field
		}
		$this->Assign("AlbumIdPairs",$album_ids);

	}
}

?>