<?php
/**
 * SongsController is the controller class for the Songs object
 *
 * @author Generated by ClassBuilder
 * @version 1.0
 */
 
require_once("verysimple/Phreeze/Controller.php");
require_once("Model/Songs.php");

class SongsController extends Controller
{

	protected function Init()
	{
		$this->ModelName = "Songs";
	}
	
	// base functions suggested to override
	// function ListAll() {}

	function ListPage()
	{
		// these parameters are supplied by extjs grid pagingtoolbar
		$s = Request::Get('start',0);  // start (zero based)
		$ps = Request::Get('limit',20); // page size
		$sc = Request::Get('sort'); // name of column for sorting
		$sd = Request::Get('dir','ASC'); // sort direction
		$cp = $s/$ps + 1; // current page
		
		require_once("Model/DAO/SongsCriteria.php");
		$criteria = new SongsCriteria();
		
		// if a sort was specified, add it to the criteria
		if ($sc)
		{
			$criteria->SetOrder($sc, ($sd == "ASC") );
		}
		
		$datapage = $this->Phreezer->Query("Songs",$criteria)->GetDataPage($cp,$ps);
		
		$this->RenderXML($datapage);
	}
	
	function Display()
	{
		$this->_AssignModel(Request::Get("Id"));
		$this->Render("SongsDisplay");
	}

	function Edit()
	{
		$this->_AssignModel(Request::Get("Id"));
		$this->Render("SongsEdit");
	}
	
	function Create()
	{
		$this->_AssignModel();
		$this->Render("SongsEdit");
	}
	
	function Save()
	{
		$pk = Request::Get("Id");
		
		$songs = $this->LoadFromForm($pk);
		
		if (!$songs->Validate())
		{
			$this->Assign("songs", $songs);
			$this->_AssignChildren($songs);
			$this->Assign("warning",implode("<br />",$songs->GetValidationErrors()));
			$this->Render("SongsEdit");
		}
		else
		{
			try
			{
				// this table does not have an auto-insert, so we have to specify an insert
				$force_insert = Request::Get("force_insert");
				$songs->Save($force_insert);
				$this->Redirect("Songs.ListAll","Songs was saved");
			}
			catch(Exception $ex)
			{
				$this->Assign("songs", $songs);
				$this->_AssignChildren($songs);
				$this->Assign("warning",$ex->getMessage());
				$this->Render("SongsEdit");
			}

		}
	}

	function Delete()
	{
		$pk = Request::Get("Id");
		$songs = $this->Phreezer->Get("Songs",$pk);
		$songs->Delete();
		$this->Redirect("Songs.ListAll","Songs was deleted");
	}

	private function _AssignModel($pk = null, $assign_children = true)
	{
		$songs = $pk ? $this->Phreezer->Get("Songs",$pk) : New Songs($this->Phreezer);
		$this->Assign("songs", $songs);

		if ($assign_children)
		{
			$this->_AssignChildren($songs);
		}
	}

	
	protected function LoadFromForm($pk = null)
	{
		// the primary key of this table is not an auto-insert
		$songs = New Songs($this->Phreezer);
		$songs->Id = Request::Get("Id");
		$songs->Name = Request::Get("Name");
		$songs->Length = Request::Get("Length");
		$songs->LyricArt = Request::Get("LyricArt");
		$songs->AlbumId = Request::Get("AlbumId");
		
		return $songs;
	}
	
	private function _AssignChildren($songs)
	{
		// get possible values for AlbumId and assign as a value pair for html_options
		$album_ids = array();
		$collection = $this->Phreezer->Query("Albums");
		while ($album_id = $collection->Next())
		{
			$album_ids[$album_id->Id] = $album_id->BandName; // TODO: verify this is the right field
		}
		$this->Assign("AlbumIdPairs",$album_ids);

		// get VSongId child records and assign as DataPage for grid display
		// if this code throws an error, check that your foreign key name is not the same as the table name
		$VSongId = $songs->GetVSongId()->GetDataPage(1,9999); // TODO: update if pagination is necessary
		$this->Assign("VSongIdDataPage",$VSongId);

	}
}

?>