<?php
/**
 * VideosController is the controller class for the Videos object
 *
 * @author Generated by ClassBuilder
 * @version 1.0
 */
 
require_once("verysimple/Phreeze/Controller.php");
require_once("Model/Videos.php");

class VideosController extends Controller
{

	protected function Init()
	{
		$this->ModelName = "Videos";
	}
	
	// base functions suggested to override
	// function ListAll() {}

	function ListPage()
	{
		// these parameters are supplied by extjs grid pagingtoolbar
		$s = Request::Get('start',0);  // start (zero based)
		$ps = Request::Get('limit',20); // page size
		$sc = Request::Get('sort'); // name of column for sorting
		$sd = Request::Get('dir','ASC'); // sort direction
		$cp = $s/$ps + 1; // current page
		
		require_once("Model/DAO/VideosCriteria.php");
		$criteria = new VideosCriteria();
		
		// if a sort was specified, add it to the criteria
		if ($sc)
		{
			$criteria->SetOrder($sc, ($sd == "ASC") );
		}
		
		$datapage = $this->Phreezer->Query("Videos",$criteria)->GetDataPage($cp,$ps);
		
		$this->RenderXML($datapage);
	}
	
	function Display()
	{
		$this->_AssignModel(Request::Get("Id"));
		$this->Render("VideosDisplay");
	}

	function Edit()
	{
		$this->_AssignModel(Request::Get("Id"));
		$this->Render("VideosEdit");
	}
	
	function Create()
	{
		$this->_AssignModel();
		$this->Render("VideosEdit");
	}
	
	function Save()
	{
		$pk = Request::Get("Id");
		
		$videos = $this->LoadFromForm($pk);
		
		if (!$videos->Validate())
		{
			$this->Assign("videos", $videos);
			$this->_AssignChildren($videos);
			$this->Assign("warning",implode("<br />",$videos->GetValidationErrors()));
			$this->Render("VideosEdit");
		}
		else
		{
			try
			{
				// this table does not have an auto-insert, so we have to specify an insert
				$force_insert = Request::Get("force_insert");
				$videos->Save($force_insert);
				$this->Redirect("Videos.ListAll","Videos was saved");
			}
			catch(Exception $ex)
			{
				$this->Assign("videos", $videos);
				$this->_AssignChildren($videos);
				$this->Assign("warning",$ex->getMessage());
				$this->Render("VideosEdit");
			}

		}
	}

	function Delete()
	{
		$pk = Request::Get("Id");
		$videos = $this->Phreezer->Get("Videos",$pk);
		$videos->Delete();
		$this->Redirect("Videos.ListAll","Videos was deleted");
	}

	private function _AssignModel($pk = null, $assign_children = true)
	{
		$videos = $pk ? $this->Phreezer->Get("Videos",$pk) : New Videos($this->Phreezer);
		$this->Assign("videos", $videos);

		if ($assign_children)
		{
			$this->_AssignChildren($videos);
		}
	}

	
	protected function LoadFromForm($pk = null)
	{
		// the primary key of this table is not an auto-insert
		$videos = New Videos($this->Phreezer);
		$videos->Id = Request::Get("Id");
		$videos->Name = Request::Get("Name");
		$videos->SongId = Request::Get("SongId");
		
		return $videos;
	}
	
	private function _AssignChildren($videos)
	{
		// get possible values for SongId and assign as a value pair for html_options
		$song_ids = array();
		$collection = $this->Phreezer->Query("Songs");
		while ($song_id = $collection->Next())
		{
			$song_ids[$song_id->Id] = $song_id->Length; // TODO: verify this is the right field
		}
		$this->Assign("SongIdPairs",$song_ids);

	}
}

?>